canonical/layer-basic

hooks/install
Error that came up when testing the fix for juju/charm-tools#58.  I think that it is dependent on the order which the `glob()` returns the files.
=> Fixed "no matching distribution" error when installing "wheelhouse"

hooks/upgrade-charm, layer.yaml, lib/charms/bootstrap.py, lib/charms/layer.py
Allow layers to define additional packages to install at time of bootstrap
=> Packages definition

README.md, hooks/config-changed, hooks/hook.template, hooks/install, hooks/leader-elected, hooks/leader-settings-changed, hooks/start, hooks/stop, hooks/update-status, hooks/upgrade-charm, lib/charms/layer/basic.py
Now you can detect config value changes with states:
```python
@when('config.changed')
def any_config_changed():
pass
@when('config.changed.my-option')
def my_option_changed():
pass
```
=> Added config states

Makefile
`make lint` will fail if not all of the directories are present.  Also, the `--exclude hooks/charmhelpers` is no longer needed, with charmhelpers being in the wheelhouse.
=> Fix lint make target

Makefile
Bundletester will discover and run Amulet tests and `juju test` is defunct.  This was causing spurious failures.
=> Remove failing `make test` target

Makefile
The build target should only be run from the charm (source) layer, so having it in the base layer is pointless.  It belongs in the reactive charm template.
=> Remove non-useful build target

lib/charms/layer/basic.py
Creating venvs in network-restricted environments (on Xenial, at least) attempts to pull `setuptools` and `wheel` from pypi.  Per pypa/virtualenv#412 `--never-download` is to be set by default to address this, but isn't yet in the packaged versions, so we need to add it manually.
=> Fix use_venv on restricted-network environments

README.md, bin/layer_option, lib/charms/layer/basic.py
```bash
. charms.reactive.sh
@when 'state'
function do_thing() {
if layer_option foo enable-bar; then
juju-log "Bar is enabled"
juju-log "bar-value is: $(layer_option foo bar-value)"
for val in $(layer_option foo arr-value); do
juju-log "val: $val"
done
fi
}
reactive_handler_main
```
=> Add CLI for layer options

README.md, lib/charms/layer/basic.py
New state to detect if a config option has been changed from its default value.  (Arguably, that's what `config.set.X` should have done from the beginning, as it seems the more useful case, but having both isn't bad.)
I'm open to bike shedding on the state name.
=> Added config.non-default.X state

README.md, lib/charms/layer/basic.py
Reverts juju-solutions/layer-basic#57
Import yaml is failing on trusty. Reverting until we fix this in the PR 
unit-sparkb-0[3311]: 2016-04-22 17:22:41 INFO unit.sparkb/0.install logger.go:40   File "lib/charms/layer/basic.py", line 4, in <module>
unit-sparkb-0[3311]: 2016-04-22 17:22:41 INFO unit.sparkb/0.install logger.go:40     import yaml
unit-sparkb-0[3311]: 2016-04-22 17:22:41 INFO unit.sparkb/0.install logger.go:40 ImportError: No module named 'yaml'
u
=> Revert "Added config.non-default.X state"

Makefile, tox.ini
This lets us use python 3.4 or python 3.5, and sets up the PATH for flake8
=> allow python 3.5 to be used

lib/charms/layer/basic.py
It is valid for entries in config.yaml to have Null values so use get
to retreive keys to avoid raising KeyError.
This closes juju-solutions/layer-basic#64
=> Cope with config.yaml entry with Null value

lib/charms/layer/basic.py
In Xenial, the `python-virtualenv` package was split in to three different packages: `python-virtualenv`, `python3-virtualenv`, and `virtualenv` with the latter installing the actual CLI command.  Unfortunately, `python-virtualenv` only recommends `virtualenv` so we have to manually install it on Xenial.  It also doesn't exist on trusty, so that's fun.
=> Fix virtualenv for xenial

wheelhouse.txt
It looks like something was pulling in pip 8.1.1 before we get to handling the wheelhouse, causing the attempted install of pip 7.1.2 to fail:
```
unit-openvim-controller-0: 2016-05-25 18:31:45 INFO unit.openvim-controller/0.install logger.go:40 Processing ./wheelhouse/pip-7.1.2.tar.gz
unit-openvim-controller-0: 2016-05-25 18:31:45 INFO unit.openvim-controller/0.install logger.go:40 Exception:
unit-openvim-controller-0: 2016-05-25 18:31:45 INFO unit.openvim-controller/0.install logger.go:40 Traceback (most recent call last):
unit-openvim-controller-0: 2016-05-25 18:31:45 INFO unit.openvim-controller/0.install logger.go:40   File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1006, in check_if_exists
unit-openvim-controller-0: 2016-05-25 18:31:45 INFO …
```
=> bump pip version range

lib/charms/layer/basic.py
This is an unlikely vector for compromise, but it can't hurt to be safe here.
=> init_config_states(): use yaml.safe_load() to parse config.yaml

lib/charms/layer/basic.py
Actions written in Python need to activate the venv, if enabled.  This is handled automatically for reactive charms in normal hooks, but we need to provide a helper to handle it in actions.
=> Refactor venv activation to helper, for actions

lib/charms/layer/basic.py
Occasionally, apt would not be able to acquire the lock and would fail, only to succeed on the next attempt.
Fixes #91
=> Retry failed apt install during bootstrap

README.md, hooks/config-changed, hooks/hook.template, hooks/install, hooks/leader-elected, hooks/leader-settings-changed, hooks/start, hooks/stop, hooks/update-status, hooks/upgrade-charm, lib/charms/layer/__init__.py, lib/charms/layer/basic.py, lib/charms/layer/execd.py
[CHARM_DIR is legacy](https://github.com/juju/juju/blob/staging/worker/uniter/runner/context/context.go#L572)
Discovered while trying to execute the collect-metrics hook in the reactive framework.
Related: https://github.com/CanonicalLtd/layer-metrics/issues/5
=> Use JUJU_CHARM_DIR environment variable

bin/layer-basic-wrapper, bin/layer_option, layer.yaml, lib/charms/layer/basic.py
Increase isolation for charms by default by switching to `use_venv: true` by default.  This should reduce confusion by novice and expert charmers alike by making it much less likely that charm dependencies, particularly versions of charmhelpers and charms.reactive, don't conflict and cause unexpected downgrades.
This also switches to `include_system_packages: true` by default as well so that the default venv doesn't block use of apt installed Python libs, though this should be rare anyway.
Finally, this also creates system-level wrappers for the CLI interfaces for this layer, charms.reactive, and charmhelpers which figure out and activate the correct venv or fall back to the system script if appropriate.
Fixes #104
Also fixes juju-solutions/charms.reactive#135
=> Change use_venv and include_system_packages default values

bin/charm-env, bin/layer-basic-wrapper, lib/charms/layer/basic.py
To make activating venvs easier for actions and other charm scripts, layer-basic-wrapper can now be used as the shebang line, where it will ensure that the proper venv is activated and `$JUJU_CHARM_DIR/lib` added to your `PYTHONPATH`  prior to invoking your script.
=> Allow layer-basic-wrapper to be used as shebang

lib/charms/layer/basic.py, wheelhouse.txt
We need to ensure that setuptools and setuptools_scm are
refreshed every now and again. This PR ensures we upgrade them
before installing anything else in the venv.
Fixes: https://github.com/juju-solutions/layer-basic/issues/110
Signed-off-by: jamesbeedy <jamesbeedy@gmail.com>
=> ensure setuptools and setuptools_scm are latest

tox.ini
In our case, we want no tests to mean there is simply nothing to test and that is ok.
=> Empty tests return error code 5, which is seen as an actual error.

lib/charms/layer/__init__.py
The backwards compatibility hack from #116 doesn't work on trusty because it has Python 3.4.  This makes it work with 3.4 / trusty with even more hackery.
Depends on juju-solutions/layer-options#3 (merged)
Depends on juju-solutions/layer-status#4 (merged)
Fixes #117
Fixes juju-solutions/charms.reactive#185
=> Make compatibility hack work for Python 3.4 (trusty)

lib/charms/layer/basic.py
Installing the python3-pip package will normally also install the
build-essential and python3-wheel packages, because it recommends
them and a normal Juju provisioned machine uses the default Ubuntu
behavior. Many charms rely on these packages, so that the embedded
Python dependencies declared in wheelhouse.txt can be installed.
In some situations, the python3-pip recommended packages do not get
installed and charms fail. This occurs when site policy changes
apt behavior to not implicitly install recommended packages. It
may also occur when a subordinate charm is installed on a machine
where python3-pip has already been installed but its recommended
packages have not (although, in practice, this situation was likely
triggered by site policy).
In any case, it does not hurt to explicitly …
=> Explicitly install python3-pip recommended packages

lib/charms/layer/basic.py
There seems to be some sort of image or race condition that causes bootstrap to fail on bionic due to missing packages.
Fixes #113
=> Run apt update if bootstrap fails

hooks/upgrade-charm, lib/charms/layer/basic.py
After a series upgrade, the venv needs to be completely rebuilt to account for updates to the system's Python.  This PR also moves the logic for upgrade-charm wheelhouse updates out of the hook code so that
that logic is all in one spot and so we can drop the specialized hook code when the hook template improvements get into stable in the charm snap.
=> Rebuild venv for post-series-upgrade hook

layer.yaml, lib/charms/layer/basic.py
There are cases where Python packages require compilation on the target system architecture and thus can't be packaged in the wheelhouse.  This allows them to be installed as part of the normal bootstrap process so they don't need to be manually managed by the charm and do the right thing with regard to the venv.
=> Add python_packages layer option

lib/charms/layer/basic.py
The option 'python_packages' was being accessed with
`cfg['python_packages']
`
instead of with
`cfg.get('python_packages')
`
like every other option. It's irrelevant if the option exist on the config.yaml or not, just trying to access it this way will give a python error of non existing key.
=> Fix config option access in the code.

bin/charm-env
To disambiguate cases where there are multiple charms co-located on a single machine, add a `--charm` option to the `charm-env` command.
Note that this specifies the name of the charm, not the application or unit name, since the latter two change depending on how it is deployed.
Fixes #109
=> Add --charm option to charm-env

bin/charm-env, lib/charms/layer/basic.py
If two charms are co-located or subordinate with differing versions of the charm-env helper it can cause issues if the older version gets installed. This change adds a version number to the helper and logic
during the bootstrap to detect the installed version and upgrade it only if its own version is newer. It will also re-do the check for every hook, to handle the case where an older charm without this logic overwrites it after the fact.
Fixes #136
=> Add version to charm-env and prevent downgrades

lib/charms/layer/basic.py
Python3 seems to throw a FileNotFoundError not CalledProcessError
if the script being called via subprocess is absent. Closes #138
=> FileNotFoundError in install_or_update_charm_env

lib/charms/layer/basic.py
On Trusty pkg_resources is not available as the python3 version of the
package is not installed by default.
Try the import and then install the python3-pkg-resources on import
failure.
Closes Issue: https://github.com/juju-solutions/layer-basic/issues/142
=> Install python3-pkg-resources on Trusty

wheelhouse.txt
Newer versions of pip (>=19.0) don't work with older versions of setuptools (<40) due to an attribute error.  If `include_system_packages` is `false` (now the default), this is not an issue because of the newer setuptools that gets installed into the venv. However, when it's `true`, which is required for some charms, the install fails because pip somehow prefers the older system-installed setuptools over the newer one in the venv. Pinning pip avoids the problem until we can find a better solution.
See:
* https://discourse.jujucharms.com/t/wheel-building-fails-during-charm-deployment/1947
* https://github.com/pypa/pip/issues/6164
=> Fix deploy error due to new pip / old setuptools conflict

lib/charms/layer/basic.py
This patch fixes issue #146, where a charm that sets `use_venv: False`
breaks on install, by adding the `--ignore-installed` flag when
pip installing the wheelhouse deps
=> Fix issue 146

tests/bundles/minimal.yaml, tests/charm-minimal/metadata.yaml, wheelhouse.txt
The last versions of Jinja2 and PyYAML to support Python 3.4 are
2.10.1 and 5.2, respectively. In order to continue supporting
Ubuntu Trusty, which defaults to Python 3.4, the wheelhouse.txt
is updated to ensure newer versions aren't used.
=> Pin Jinja2/PyYAML in wheelhouse.txt for Python 3.4

lib/charms/layer/basic.py
This adds discovery of "centos6", "centos7" and "rhel" linux distributions that are using "yum" as package manager.
The juju layers: "basic" & "options", both fails on at least centos6 and centos7 which are both supported in MAAS clouds. This is needed by "SLURM" charms/bundles running HPC workloads - for example. This is also a huge stopper for a broader adoption of juju for "non ubuntu" OS:es.
See this thread: https://discourse.jujucharms.com/t/charms-for-centos-lets-begin/2339/16
This code is a prerequisite to be able to run reactive charms at all with OS:es using "yum".
The charm-helpers package also need fixes to get "yum" like OS:es to run python reactive charms. 
As of today, in charm-helpers this code will fail:
`import yum`
This import will cause an error since "yum" its not …
=> Fixed the support for centos and rhel

.travis.yml, .travis/profile-update.yaml, lib/charms/layer/basic.py, tests/bundles/minimal.yaml, tests/charm-minimal/metadata.yaml, tests/tests.yaml
Focal provides a newer version of pip (and setuptools) than what is bundled, and downgrading it in the venv leads to it being broken. This doesn't show until after the first bootstrap, so it fails on the first `upgrade-charm` hook rather than the `install` hook. This skips installing pip and setuptools if pip is already at a newer version in the venv.
Fixes #159
=> Fix broken pip due to downgrade on Focal+

.travis.yml, tests/charm-minimal/layer.yaml, tests/charm-minimal/wheelhouse.txt, tox.ini
At present we have enabled excessive debug-logging to accompilsh
the same thing, but that makes it unpleasant to look at.
Change permissions on the LXD socket to give travis user access
instead of using the sudo back to ourself trick as it leads to
some unwanted complexity.
Add Python 3.8 target to test matrix.
Closes #161
=> Use ``travis_wait`` to keep func test alive

lib/charms/layer/basic.py
The workaround for https://github.com/pypa/pip/issues/410 is no longer needed on newer Ubuntu releases and fails entirely now on Focal.
See discussion on #156, which this replaces with a slightly more conservative approach.
Fixes #149
=> Remove allow_hosts workaround for Focal and after

.travis.yml, lib/charms/layer/basic.py, tests/bundles/minimal.yaml, tests/charm-minimal-no-venv/layer.yaml, tests/charm-minimal-no-venv/metadata.yaml, tox.ini
The change in #167 to use `--force-reinstall`, while significantly safer overall does fail on bionic and earlier when using `use_venv: false`. This was missed in the existing functional tests, so this first adds tests to cover that and ensure that things like this will be caught going forward, then adds a fix to use `--force-reinstall` when possible but otherwise fall back to the previous `--ignore-installed` behavior.
Fixes #168
=> Fix reinstall error with use_venv: false on bionic and earlier.

lib/charms/layer/basic.py, unit_tests/test_lib_charms_layer_basic.py
LANG is used to determine the default decoder when reading files in
Python. If it isn't set, some python versions simply default to ASCII
which leads to errors in some cases during Python package installation.
Juju did not set LANG in hook environments until 2.7 where it started to
add LANG=C.UTF-8. In order to support pre-2.7 environments where the
presence of LANG is significant during the package installation and
upgrades, let's add LANG explicitly if it is not set.
Fixes: #173
=> Add LANG=C.UTF-8 if it isn't set for subprocesses

wheelhouse.txt
netaddr 0.7.20 pulls in importlib-resources, which depends on a newer
version of setuptools_scm than we use.  It also pulls zipp, which
depends on a newer version of setuptools than we use.  Pinning to
0.7.19 avoids this.
=> Pin netaddr

.travis.yml, lib/charms/layer/basic.py
This change prevents the wheelhouse installation from accessing the
network at all.  This allows it to install quickly behind firewalls that
silently drop packets causing long delays in installing the packages if
a dependency is 'later' in the wheelhouse install, which is done in
directory order (usually alphabetically).
Closes launchpad bug: #1884449
=> Stop pip3 AND easy_install from accessing network on install

tests/bundles/minimal.yaml
Eoan has been EOLed and no longer has images available, so it gets stuck in pending and causes the functional tests to hang.
=> Remove Eoan from functional tests

lib/charms/layer/basic.py
The change in #182 used undocumented methods / attributes of the Requirement class which worked on newer releases of setuptools but not on the one available in trusty, leading to functional test failures.
=> Fix incompatible usage of Requirement

lib/charms/layer/basic.py
Major upgrades of setuptools SCM break with pre-existing versions [0].
Remove the venv on charm upgrades to avoid this and other potential problems.
Tested with Octavia.
Closes-Bug: #1891639 [1]
[0] https://github.com/fink/fink-distributions/issues/219
[1] https://bugs.launchpad.net/charm-octavia/+bug/1891639
=> Clear the venv on all upgrades

bin/charm-env
There's a case where charm-env can create spurious warnings about failing to import charmhelpers when trying to determine the charm name for a given charm directory.  This avoids that by using `grep` and `sed` in place of trying to properly parse the yaml.
This also fixes an issue with subordinates that are built with `charm build` or otherwise use quotes around the `subordinate` field from being incorrectly identified as non-subordinate.  This should only affect interactive usage and should cut down on the "ambiguous possibilities" messages and be more DWYM.
Fixes #140
=> charm-env: Fix spurious import warning and not handling all subordinates properly

lib/charms/layer/basic.py
pip 20.3.4 and higher fail to install the packages specified in the
wheelhouse if versions are not used directly.  This patch uses the
'package==version' method of specifying a versio for a package when
installing the packages from the wheelhouse (which ought to be all of
them).
=> pip 20.3+ compatibility: use wheelhouse versions on install

.github/workflows/main.yml, wheelhouse.txt
MarkupSafe 2.0.0+ (required for Jinja2) removed py35 compatability, so
we need to pin it for charms to work on xenial.
Closes-bug: #196
=> Pin MarkupSafe < 2.0.0 for py35 support

.github/workflows/main.yml, README.md, lib/charms/layer/basic.py, test-requirements.txt, tests/bundles/minimal.yaml, tests/charm-minimal/wheelhouse.txt, tox.ini, wheelhouse.txt
To ensure compatibility with newer Pythons unpin some requirements
when building in environments with later Pythons.
This resolves compability issues with new Pythons and is OK as
charms can now be build on the Ubuntu release that they will also
run on.
=> Tweak dependency versions for newer Pythons

wheelhouse.txt
It would be wonderful if we could just have these unpinned and
use the latest and gratest, but unfortunately new releases
routinely bring incompatible and braking changes.
The consequence is released charms breaking after a rebuild, and
more often than you would think we actually encounter changes
in the dependency change between charm CI run and merge, leading
to upload of broken charms to charmhub, which is unacceptable.
=> Pin pip and setuptools

wheelhouse.txt
Builds are failing due to setuptools_scm issue
722 *1 . To work around this pin setup tools.
*1 https://github.com/pypa/setuptools_scm/issues/722
=> Pin setuptools-scm for py ge 3.8

lib/charms/layer/basic.py, tests/bundles/minimal.yaml, tox.ini, unit_tests/test_lib_charms_layer_basic.py
The file naming convention for Python source wheels and built binary wheels are quite different.
Update the code so that it can extract package name and versions from both wheel types.
Signed-off-by: Frode Nordahl <frode.nordahl@canonical.com>
=> Support installing charms with built wheels

.github/workflows/main.yml, tox.ini, wheelhouse.txt
ops>=2.1.0 depends on PyYAML-6.x[0], allowing the installation of that version in layer-basic and the charm using layer-basic can lockdown on a more specific version of PyYAML.
It's important to keep reactive charms compatible with the ops framework, because there are compatibility layers to allow the use of interfaces in ops framework based charms[1]
[0] https://github.com/canonical/operator/commit/9162c873592499f512b2ea3908cf9578c0fcc4b8
[1] https://github.com/openstack/charm-interface-hacluster/commit/34b12aa480bc7d6d44699461fa21cb358c5089b4
=> Allow PyYAML 6.x

wheelhouse.txt
Fixes error when installing pyaml tarball.
Requested unknown from file://[...]/charm/wheelhouse/pyaml-23.5.9.tar.gz \
has inconsistent name: filename has 'pyaml', but metadata has 'unknown'
Closes-Bug: http://pad.lv/2020788
=> Pin pyaml<23.0.0

wheelhouse.txt
Pin Cython due to [1], but also to stop future madness, pin the rest of
the wheelhouse.txt to less than next major version. These pins will need
updating from time to time.
The Cython release to 3.0.0 broke pyyaml which (even as of 6.0.1)
requires cython < 3.0.0 to install. This needs pinning here as otherwise
Cython 3.0 gets installed before pyyaml and then it just breaks.
[1] https://github.com/yaml/pyyaml/issues/724
=> Pin Cython < 3.0 and the rest of the unpinned wheelhouse.txt

wheelhouse.txt
flit_scm is required by exceptiongroup.
anyio is pinned to prevent requiring setuptools >= 64.
Fixes #218
=> Add flit_scm and anyio pins to wheelhouse

.github/workflows/main.yml, tox.ini, wheelhouse.txt
The version of setuptools pinned by the wheelhouse is incompatible with python 3.12, to avoid breaking old charms, this patch unpins setuptools only for python>=3.12
Fixes the following error at build time:
File "/tmp/pip-download-gg1zdrmr/setuptools_ebd74bdeeaf0421480a69f5448330f5e/setuptools/__init__.py", line 16, in <module>
import setuptools.version
File "/tmp/pip-download-gg1zdrmr/setuptools_ebd74bdeeaf0421480a69f5448330f5e/setuptools/version.py", line 1, in <module>
import pkg_resources
File "/tmp/pip-download-gg1zdrmr/setuptools_ebd74bdeeaf0421480a69f5448330f5e/pkg_resources/__init__.py", line 2191, in <module>
register_finder(pkgutil.ImpImporter, find_on_path)
^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
=> Unpin setuptools for Python>=3.12

lib/charms/layer/basic.py
Using older virtualenv with setuptools above version 60 can lead to undesirable behavior. Example of these problems are:
* Unexpected layout within the virtual environment
* Failure to isolate virtual environment from system-wide packages
Fixes #225
=> Update virtualenv along with setuptools.

wheelhouse.txt
Fixes https://github.com/canonical/layer-basic/issues/223
=> sniffio is pulled in for anyio, it is not needed otherwise so make it match

wheelhouse.txt
immutables >= 0.16 requires setuptools >= 42,
but setuptools is pinned to <42 for python 3.8 (for bionic base).
Fixes: #223
=> Pin immutables to <0.16 on bionic to fix install

.github/workflows/main.yml, wheelhouse.txt
Pinning pbr<6.1.1 to deal with install hook issue on reactive charms that depend on `charmhelpers`.
Layer basic pins setuptools to a version which cannot install pbr.
```sh
2025-02-11 21:18:08 DEBUG unit.openstack-integrator/0.install logger.go:60 Processing ./wheelhouse/pbr-6.1.1.tar.gz
2025-02-11 21:18:08 DEBUG unit.openstack-integrator/0.install logger.go:60   Installing build dependencies: started
2025-02-11 21:18:09 DEBUG unit.openstack-integrator/0.install logger.go:60   Installing build dependencies: finished with status 'error'
2025-02-11 21:18:09 WARNING unit.openstack-integrator/0.install logger.go:60   error: subprocess-exited-with-error
2025-02-11 21:18:09 WARNING unit.openstack-integrator/0.install logger.go:60   
2025-02-11 21:18:09 WARNING …
```
=> Pinning pbr<6.1.1 so it continues to use setuptools
